<template>
  <v-app>
      <NavMenu/>
      <v-main>
        <h2>FAQs</h2>

        <dl>
          <div v-for="(faq, i) in faqs" :key="i">
            <dt>{{ faq.q }}</dt>
            <dd>{{ faq.a }}</dd>
          </div>
        </dl>
      </v-main>
  </v-app>
</template>

<script>
import NavMenu from "../components/NavMenu.vue";

export default {
  components:{
      NavMenu,
  },

  data() {
    return {
      faqs: [
        {
          q: 'How do I buy solar cells?',
          a: 'Buying solar cells is easy. Simply Sign up, head to the Project page, select an open crowdsale and click/tap on the “buy cells” button.',
        },
        {
          q: 'What’s the assurance that Sunswitch will remain in business in the next 5 years and continue to pay me?',
          a: 'As a registered subsidiary of Greenera Technologies, which is funded and backed by local and international investors, all our projects are insured, and your investment is backed by a contract which will allow you to continue earning from it being used, no matter what happens to the company',
        },
        {
          q: 'What payment methods do we accept?',
          a: 'We accept credit cards, direct bank transfers through our third party banking service provider in Flutterwave.',
        },
        {
          q: 'Why do I need to verify my identity?',
          a: 'In order for us to comply with international KYC/AML (Know Your Customer/Anti-Money Laundering) regulations we need to verify your identity. It would take more than 2 minutes of your time.',
        },
        {
          q: 'How much can I earn per month?',
          a: 'Your monthly earning potential is entirely linked to the amount of electricity generated by your solar cells in a specific project during that period. Your earnings will be lower in winter versus summer. The estimates we give are annualized averages. Not all projects have the same earning potential, so be sure to read all the details of the projects before sponsoring.',
        },
        {
          q: 'How do I get paid?',
          a: 'Your monthly solar income is paid into your dashboard wallet in the local currency of your choice. The monthly income you accumulate can be used to buy more solar cells in other solar projects, or withdrawn to a bank account in the local country of the project.',
        },
        {
          q: 'Can I have my solar rental income paid into my bank account directly?',
          a: 'No, your monthly solar income is paid into your Sunswitch dashboard wallet, However, you can withdraw solar income earned in fiat currency if you have a bank account in the country of that currency. If you don’t, you can also make withdrawal but, please note that International bank transfers are expensive. To enable you to receive your solar income anywhere in the world easier with little or no charges, we plan to offer payment in crypto currency in the future.',
        },
        {
          q: 'How do I add a payout/withdrawal account?',
          a: 'Simply navigate to your dashboard, click/tap on the “account setting” > “add accounts” tab and then add your payout account.',
        },
        {
          q: 'How often is rental paid?',
          a: 'Rental payments are made in the last week of the month, starting at the beginning of the month following the completed installation. These monthly payments continue for the 20-year lease period.',
        },
        {
          q: 'Can I sell my solar cells?',
          a: 'The solar cell product isn\'t designed to be re-sold. They are on a 20-year solar cell lease for long term income. Think of it like buying solar panels for your house. It’s a long-term commitment. \nA secondary market where you can resell may be a feature we launch in the future, however this is not guaranteed.',
        },
        {
          q: 'How is my projected income determined?',
          a: 'The income is not fixed, it is based on the amount of energy generated by your solar cells; the more energy a client uses from your solar cells, the more income you make, and the internal rate of return(IRR) of a particular project.',
        },
        {
          q: 'What is IRR and how is it calculated?',
          a: 'IRR stands for internal rate of return and is the interest rate at which the net present value of all the cash flows (both positive and negative) from a project or investment equal zero. IRR is used to evaluate the attractiveness of a project or investment.',
        },
        {
          q: 'What is the guarantee that projects will keep making profit for 20 years for investors?',
          a: 'Each project is secured my multiple means of revenue generation. Projects are movable in case of bankrupcy of a client, the solar system will be moved and used to serve another business. Remember your panels can wax strong for 25years!',
        },
        {
          q: 'what is the guarantee that the solar panels will keep generating power for 20 years?',
          a: 'Solar panels has active power-generating lifespan of 25 years. Your investment is secured by the one of the longest-serving technology ever!',
        },
      ]
    };
  }
};
</script>

<style>
h2 {
  font-size: 5rem;
  text-align: center;
}

dl {
  padding: 1rem;
}

dl > div {
  margin-bottom: 2rem;
  border-radius: 1rem;
  border: 1px solid #199958;
}

dt {
  color: white;
  font-weight: 700;
  padding: 1rem 1rem 0.5rem;
  background-color: #199958;
  border-top-left-radius: 1rem;
  border-top-right-radius: 1rem;
}

dd {
  padding: 1rem;
}
</style>
